// Liar's Ledger - server/providers/store.js
// Token and scan count storage via Upstash Redis.
//
// Data model:
//   token:{id}        → JSON { tier, createdAt }
//   scans:{id}:{date} → integer (daily scan count, TTL 48h)
//
// Swap this file to migrate to PostgreSQL later —
// the interface (exported functions) stays the same.

import { Redis } from "@upstash/redis";

const redis = new Redis({
  url:   process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});

const FREE_SCANS_PER_DAY = 5;
const SCAN_TTL_SECONDS = 60 * 60 * 48; // 48h — covers timezone edge cases

function todayKey() {
  return new Date().toISOString().slice(0, 10); // "2026-06-13"
}

/**
 * Create a new anonymous token.
 * @param {string} tokenId — UUID generated by the extension
 * @param {string} tier — "free" or "pro"
 */
export async function createToken(tokenId, tier = "free") {
  const data = {
    tier,
    createdAt: new Date().toISOString(),
  };
  await redis.set(`token:${tokenId}`, JSON.stringify(data));
  return data;
}

/**
 * Look up a token. Returns { tier, createdAt } or null.
 */
export async function getToken(tokenId) {
  const raw = await redis.get(`token:${tokenId}`);
  if (!raw) return null;
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

/**
 * Increment today's scan count for a token.
 * Returns { count, limit, remaining, allowed }.
 */
export async function incrementScans(tokenId, tier = "free") {
  const key = `scans:${tokenId}:${todayKey()}`;
  const count = await redis.incr(key);

  // Set TTL on first scan of the day
  if (count === 1) {
    await redis.expire(key, SCAN_TTL_SECONDS);
  }

  const limit = tier === "pro" ? Infinity : FREE_SCANS_PER_DAY;
  const allowed = count <= limit;

  return {
    count,
    limit: tier === "pro" ? "unlimited" : FREE_SCANS_PER_DAY,
    remaining: tier === "pro" ? "unlimited" : Math.max(0, FREE_SCANS_PER_DAY - count),
    allowed,
  };
}

/**
 * Get today's scan count without incrementing.
 */
export async function getScans(tokenId) {
  const key = `scans:${tokenId}:${todayKey()}`;
  const count = (await redis.get(key)) || 0;
  return Number(count);
}

/**
 * Upgrade a token's tier (e.g., after Square payment).
 */
export async function upgradeTier(tokenId, tier) {
  const existing = await getToken(tokenId);
  if (!existing) return null;

  const updated = { ...existing, tier, upgradedAt: new Date().toISOString() };
  await redis.set(`token:${tokenId}`, JSON.stringify(updated));
  return updated;
}

/**
 * Delete a token (e.g., account cancellation).
 */
export async function deleteToken(tokenId) {
  await redis.del(`token:${tokenId}`);
}
